// Angular/app/static/angular-app/src/app/data/data.component.ts
import { Component } from '@angular/core';
import { Http } from '@angular/http';

@Component({
  selector: 'app-data',
  templateUrl: './data.component.html',
  styleUrls: ['./data.component.css']
})
export class DataComponent{
  public users: User[];

  constructor(http: Http) {
    http.get('/api/data').subscribe(result => {
      this.users = result.json() as User[];
    }, error => console.error(error));
  }
}

interface User {
  Name: string;
  Role: string;
  Status: string;
}

<h1>Users</h1>

<p *ngIf="!users"><em>Loading...</em></p>

<table class="table" *ngIf="users">
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>    
    <tr *ngFor="let user of users">
      <td>{{user.Name}}</td>
      <td>{{user.Role}}</td>
      <td>{{user.Status}}</td>
    </tr>    
  </tbody>
</table>

// React/app/static/react-app/src/Data.tsx
import * as React from 'react';

interface DataState {
    users: User[];
    loading: boolean;
}

export class Data extends React.Component<{}, DataState> {
    constructor(props: {}) {
        super(props);
        this.state = { users: [], loading: true };

        fetch('api/data')
            .then(response => response.json() as Promise<User[]>)
            .then(data => {
                this.setState({ users: data, loading: false });
            });
    }

    public render() {
        let contents = this.state.loading
            ? <p><em>Loading...</em></p>
            : this.renderUsersTable(this.state.users);

        return (
            <div>
                <h1>Users</h1>
                {contents}
            </div>
        );
    }

    private renderUsersTable(users: User[]) {
        return(
            <table className="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Role</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {users.map(user =>
                        <tr key={user.Name}>
                            <td>{user.Name}</td>
                            <td>{user.Role}</td>
                            <td>{user.Status}</td>
                        </tr>
                    )}
                </tbody>
            </table>
        );
    }
}

interface User {
    Name: string;
    Role: string;
    Status: string;
}
